### PR TITLE
Fixed IE11 Problem - webViewerLoad needs an empty string

### PR DESCRIPTION
**Pull request by apeinsip**
There is a problem with current master - if you use IE11. The webViewerLoad needs an empty string. Would need urgent an new version.

image

### CODE REVIEW

**Comment by apeinsip** [comment]
I have forgotten to update file in dist path - if you accept the PR please update file in dist path

**Comment by moesjarraf** [comment]
Thanks for the PR, it does solve the problem.

Could you please update the dist yourself though, since the PR is now incomplete, and merging an incomplete PR in to master isn't nice.

**Comment by apeinsip** [comment]
New Pull request

**Comment by apeinsip** [comment]
Fixed IE11 Problem - webViewerLoad needs an empty string. Update dist - please organize a bower update

**Review by moesjarraf — APPROVED** [review]

**Pull request merged**
